---
name: CI

on: [push]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        id: checkout
        uses: actions/checkout@v4

      - name: "Run Tests"
        id: run_tests
        run: ./run-tests

      - name: "Run Against Spec"
        id: run_spec
        run: ./run-spec
